services:
  # Laravel管理画面用コンテナ
  app:
    build:
      context: ./docker/backend/
      dockerfile: Dockerfile
    container_name: tokyu_branz_app
    volumes:
      - ./tokyu_branz:/var/www/html
    ports:
      - 8083:80
    depends_on:
      - db
    # 環境変数を必要に応じて追加できます
    environment:
      # Laravel アプリケーションで DB 接続するための設定例
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password

  # MySQLコンテナ
  db:
    image: mysql:8
    container_name: tokyu_branz_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # データを永続化するためにボリュームを設定
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306"

  # phpMyAdmin コンテナ
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: tokyu_branz_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8003:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password

  # Reactフロントエンドコンテナ
  frontend:
    build:
      context: ./ # プロジェクトルートをビルドコンテキストにする
      dockerfile: ./docker/frontend/Dockerfile
    container_name: tokyu_branz_frontend
    volumes:
      - ./tokyu_branz_frontend:/app
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production

# ここで定義したボリュームを DB で使います
volumes:
  db-data:
